### ISSUE TITLE
Consider hosting project under pytest-dev

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-github-actions-annotate-failures#33]
Have you considered hosting this plugin under @pytest-dev organization? The process can be initiated with a ticket on https://github.com/pytest-dev/meta/issues

I am asking this because I am not keen to add dependency on plugins that can easily become unmaintained. (happened multiple times in the past).

I am also a python plugin author and I did that to make the future of the plugin safer.

**Comment by utgwkk** [comment]
:+1: That's a good idea. I'm going to prepare for [requirements of transferring repository to pytest-dev](https://docs.pytest.org/en/stable/contributing.html#submitting-plugins-to-pytest-dev) (there are no tox configuration or changelog file in this repository now).

**Comment by utgwkk** [comment]
@ssbarnea I prepared changelog and tox configuration (I think this plugin is ready to be transferred). Can I submit an issue of migrating this plugin to pytest-dev/meta (or should I do something else more)?

**Comment by ssbarnea** [comment]
Please create a ticket, I will try to help with it. Is better if owner is proposing it, for obvious reasons.

**Comment by utgwkk** [comment]
I see.

**Comment by utgwkk** [comment]
I created a ticket https://github.com/pytest-dev/meta/issues/9. Thank you for your help!
