### ISSUE TITLE
Annotate warnings as well?

### ISSUE THREAD

**Issue by mjpieters** [pytest-dev/pytest-github-actions-annotate-failures#45]
Can warnings captured by pytest also be turned into annotations? I’m referring to the warnings output at the end of a pytest run.

Pytest offers a [hook for such warnings](https://docs.pytest.org/en/6.2.x/reference.html#pytest.hookspec.pytest_warning_recorded). They could be turned into annotations using the [*warning* workflow command](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-a-warning-message).

**Comment by utgwkk** [comment]
Looks like good. It would be better that we can suppress warning annotations with some options.

**Comment by edgarrmondragon** [comment]
Started a PR #68

**Comment by oliv10** [comment]
I would like to see this implemented. And the PR has been stale for nearly a year... and is fully functional, I pulled and tested it myself. Works as expected.

+1

**Comment by edgarrmondragon** [comment]
> I would like to see this implemented. And the PR has been stale for nearly a year... and is fully functional, I pulled and tested it myself. Works as expected.
> 
> +1
> 
> Screenshot (Ran in a matrix, works great)
> <img alt="image" width="1346" src="https://private-user-images.githubusercontent.com/18117030/330544902-afb7f80c-4f89-4999-87df-ad7045b6515f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTA4ODcsIm5iZiI6MTcxNTcxMDU4NywicGF0aCI6Ii8xODExNzAzMC8zMzA1NDQ5MDItYWZiN2Y4MGMtNGY4OS00OTk5LTg3ZGYtYWQ3MDQ1YjY1MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE4MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNTY2YjMzZTNmMDQ1NzQxOGEyY2EzZDZiNjU4M2ViZjk5Mzk2MTNmODdjMzgwNWUxN2Q2MmQ1OTA2YjFkYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dyGECHteYB1tt8AisyJEQgkvOBkX-0oV4PbEi-e8DvU">

@oliv10 thanks for giving it a try! Tests are failing for pytest 7.4.x on that PR, so I need to make some time to fix that. It's probably also worth adding tests for 8.x in a separate PR.

**Comment by oliv10** [comment]
@edgarrmondragon no problem! Just to make note for you, I used pytest 8.2.0 in the previous screenshot.

**Comment by henryiii** [comment]
The bug (https://github.com/pytest-dev/pytest-github-actions-annotate-failures/issues/81 and more detail in https://github.com/pytest-dev/pytest-github-actions-annotate-failures/issues/76) only affects certain annotations.

**Comment by oliv10** [comment]
Still looking forward to this feature!

**Comment by BGannon2** [comment]
+1 this came up in a discussion with our developers this week. Would be very nice to have!

**Comment by edgarrmondragon** [comment]
@BGannon2 please give https://github.com/pytest-dev/pytest-github-actions-annotate-failures/pull/68 a try if you are able. I hope we can get a maintainer to review it soon.
