### ISSUE TITLE
remove usages of codecov pypi version

### ISSUE THREAD

**Issue by auvipy** [pytest-dev/pytest-github-actions-annotate-failures#69]
Collecting pytest-github-actions-annotate-failures==0.1.8
Using cached pytest_github_actions_annotate_failures-0.1.8-py2.py3-none-any.whl (5.1 kB)
ERROR: Ignored the following versions that require a different python version: 3.0.0 Requires-Python >=3.8; 3.0.1 Requires-Python >=3.8; 3.0.2 Requires-Python >=3.8; 3.0.3 Requires-Python >=3.8; 3.0.4 Requires-Python >=3.8; 3.1.0 Requires-Python >=3.8; 3.1.1 Requires-Python >=3.8; 3.2.0 Requires-Python >=3.8; 3.2.1 Requires-Python >=3.8; 3.2.2 Requires-Python >=3.8; 6.0.0 Requires-Python >=3.8.1
ERROR: Could not find a version that satisfies the requirement codecov==2.1.12 (from versions: 2.1.13)
ERROR: No matching distribution found for codecov==2.1.12

**Comment by edgarrmondragon** [comment]
This package doesn't seem to depend on `codecov` so you may looking at a different dependency

**Comment by auvipy** [comment]
I fixed the hidden one which was causing this. thanks
