### ISSUE TITLE
Drop support for older Pytest versions

### ISSUE THREAD

**Issue by edgarrmondragon** [pytest-dev/pytest-github-actions-annotate-failures#85]
I got some numbers from the downloads dataset on BigQuery:

| version | downloads (past month) | percent | last release |
| ------- | ---------------------- | ------- | ------------ |
| **4.x** | 1,446,865              | 1.1%    | 2020-06-05   |
| **5.x** | 2,464,986              | 1.9%    | 2020-06-02   |
| **6.x** | 9,514,327              | 7.3%    | 2021-08-30   |
| **7.x** | 49,503,260             | 38.1%   | 2023-12-31   |
| **8.x** | 66,480,236             | 51.1%   | 2024-04-27   |

It's probably worth at least dropping 4.x and 5.x. Curious what you think @henryiii.

**Comment by henryiii** [comment]
I’ve already dropped 4 and 5 locally. :)
